version: '3'

services:

  gblb_play:
    # このファイルと同じフォルダーのDockerfileを使う
    build: ./dockerfiles/gblb/

    links:
      - 'gblb_mysql:gblb_mysql'

    volumes:
      - .:/app
    # コンテナ名を指定する
    container_name: gblb_play

    ports:
      - '9000:9000'

  gblb_mysql:
    image: mysql
    #再起動してくれる
    restart: always

    #マウント（ホスト側パス（相対）：コンテナ内パス）
    volumes:
      - ./dockerfiles/mysql/conf.d:/etc/mysql/conf.d
      - ./dockerfiles/mysql/initsql:/docker-entrypoint-initdb.d

    environment:
      - MYSQL_ROOT_PASSWORD=1Qazxsw2#
    ports:
      - '3306:3306'
